name: api-build

on:
  push:
    paths: 
    - ".github/workflows/api-build.yml"
    - "api/**"

jobs:
  build:
    name: build-api
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: dotnet build
        working-directory: ./api/HelloWorldApi
      - uses: actions/upload-artifact@v4
        with:
          path: ./api/HelloWorldApi
          name: "something-${{ matrix.os }}"
