name: api-build

on:
  push:
    paths: 
    - ".github/workflows/api-build.yml"
    - "api/**"

jobs:
  build:
    name: build-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: dotnet build
        working-directory: ./api
