name: gh

on:
  push:
    paths:
      - ".github/workflows/gh.yml"
  workflow_dispatch:

jobs:
  cli:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - run: gh repo list
