name: gh

on:
  push:
    paths:
      - ".github/workflows/gh.yml"
  workflow_dispatch:

jobs:
  cli:
    runs-on: ubuntu-latest
    env:
      GH-TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: gh repo list
